# Generated by Django 5.2.7 on 2025-11-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='asignaciones.oficinaregional')),
            ],
            options={
                'unique_together': {('numero', 'oficina')},
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siged', models.CharField(max_length=50, unique=True, verbose_name='N.º SIGED')),
                ('tipo_supervision', models.CharField(choices=[('VISITA', 'Visita'), ('VERIFICACION', 'Verificación'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('INFORME', 'Informe'), ('ACTA', 'Acta'), ('OFICIO', 'Oficio'), ('OTRO', 'Otro')], max_length=20)),
                ('carta_linea', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('PENDIENTE', 'Pendiente'), ('CONCLUIDO', 'Concluido')], default='EN_PROCESO', max_length=20)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('fecha_derivacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignaciones.contrato')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignaciones.oficinaregional')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
