# Generated by Django 5.2.8 on 2025-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_contrato_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='visita',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
    ]
