# Generated by Django 5.2.8 on 2025-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_expediente_visita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='visita',
        ),
        migrations.AddField(
            model_name='expediente',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='visita_decision',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Visita'),
        ),
    ]
