# Generated by Django 5.2.8 on 2025-11-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_anuncio_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_derivacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de derivación'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
    ]
