# Generated by Django 5.2.8 on 2025-11-18 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_alter_anuncio_options_alter_mensaje_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_derivacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='siged',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Oficio múltiple'), ('FICHA', 'Ficha de registro de hidrocarburos'), ('INFORME', 'Informe técnico'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_supervision',
            field=models.CharField(choices=[('ORDINARIA', 'Supervisión ordinaria'), ('INOPINADA', 'Inspección inopinada'), ('ESPECIAL', 'Supervisión especial'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='visita_decision',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
