# Generated by Django 5.2.8 on 2025-11-18 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0007_remove_expediente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='codigo_actividad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expediente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_asignacion',
            field=models.DateField(default=datetime.date(2025, 11, 18)),
            preserve_default=False,
        ),
    ]
