# Generated by Django 5.2.8 on 2025-11-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0009_expediente_created_at_expediente_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
