# Generated by Django 5.2.8 on 2025-11-21 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0010_expediente_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='destino',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='remitente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('asignacion', 'Asignación'), ('informativo', 'Informativo')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
