# Generated by Django 5.2.8 on 2025-11-27 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0012_alter_anuncio_options_remove_anuncio_leido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expediente', 'verbose_name_plural': 'Expedientes'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='expediente',
            name='siged',
            field=models.CharField(max_length=50, unique=True, verbose_name='N° SIGED'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Supervisor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='visita_decision',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
    ]
