# Generated by Django 5.2.8 on 2025-11-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0013_alter_contrato_options_alter_expediente_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={},
        ),
        migrations.AddField(
            model_name='anuncio',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='destinatario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_recibidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='grupo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='remitente',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('URGENTE', 'Urgente')], max_length=50),
        ),
    ]
