# Generated by Django 5.2.8 on 2025-11-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0014_alter_anuncio_options_anuncio_leido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Supervisión',
                'verbose_name_plural': 'Tipos de Supervisión',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['numero'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='oficinaregional',
            options={'ordering': ['nombre'], 'verbose_name': 'Oficina Regional', 'verbose_name_plural': 'Oficinas Regionales'},
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignaciones.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_supervision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignaciones.tiposupervision'),
        ),
    ]
