# Generated by Django 5.2.8 on 2025-11-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0015_tipodocumento_tiposupervision_alter_anuncio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='oficinaregional',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='tiposupervision',
            options={'verbose_name': 'Tipo de Supervisión', 'verbose_name_plural': 'Tipos de Supervisión'},
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaciones.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaciones.tiposupervision'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='visita_decision',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposupervision',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
