# Generated by Django 5.2.8 on 2026-01-21 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0019_anunciolectura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='leido',
        ),
        migrations.AlterField(
            model_name='anunciolectura',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='asignaciones.anuncio'),
        ),
        migrations.AlterField(
            model_name='anunciolectura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_leidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnuncioEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminaciones', to='asignaciones.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('anuncio', 'usuario')},
            },
        ),
    ]
