# Generated by Django 5.2.8 on 2026-01-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0020_remove_anuncio_leido_alter_anunciolectura_anuncio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
