# Generated by Django 5.2.8 on 2026-01-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0021_alter_mensaje_options_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='eliminado_por_destinatario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='eliminado_por_remitente',
            field=models.BooleanField(default=False),
        ),
    ]
