# Generated by Django 5.2.8 on 2026-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0022_mensaje_eliminado_por_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de cumplimiento'),
        ),
    ]
