# Generated by Django 5.2.8 on 2026-02-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0023_expediente_fecha_limite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['concluido', 'fecha_limite', '-fecha_asignacion'], 'verbose_name': 'Expediente', 'verbose_name_plural': 'Expedientes'},
        ),
    ]
